### ISSUE TITLE
Server unable to start after adding plugin when Strapi is setup with Typescript 

### ISSUE THREAD

**Issue by MindDesign** [shop3/strapi-plugin-shopify#9]
# How to reproduce

* Create new Strapi project `npx create-strapi-app@latest my-project`
* Chose custom setup
* Chose Typescript
* Install plugin `npm install --save strapi-plugin-shopify`
* Run `npm run develop`

# Error log

```
Starting the compilation for TypeScript files in /home/tommy/projects/name/shopify-headless/my-project
[2022-11-29 12:26:52.448] debug: ⛔️ Server wasn't able to start properly.
[2022-11-29 12:26:52.449] error: Error regarding shopify config: 5 errors occurred
Error: Error regarding shopify config: 5 errors occurred
    at applyUserConfig (/home/tommy/projects/name/shopify-headless/my-project/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:72:13)
    at async Object.loadPlugins (/home/tommy/projects/name/shopify-headless/my-project/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:100:3)
    at async Strapi.loadPlugins (/home/tommy/projects/name/shopify-headless/my-project/node_modules/@strapi/strapi/lib/Strapi.js:333:5)
    at async Promise.all (index 2)
    at async Strapi.register (/home/tommy/projects/name/shopify-headless/my-project/node_modules/@strapi/strapi/lib/Strapi.js:369:5)
    at async Strapi.load (/home/tommy/projects/name/shopify-headless/my-project/node_modules/@strapi/strapi/lib/Strapi.js:474:5)
    at async Strapi.start (/home/tommy/projects/name/shopify-headless/my-project/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
```

# Versions
* Version: 4.5.2 (node v16.17.1
* Edition: Community

**Comment by MindDesign** [comment]
Actually, this happens when selecting the recommended setup as well. Thought I had installed the plugin when tested the default setup, but alas, I hadn't.

**Comment by j4m3sb0mb** [comment]
This error is because the plugin needs environment variables or a configuration in plugins.ts

**Comment by j4m3sb0mb** [comment]
Maybe the error should be more explicit

**Comment by MindDesign** [comment]
That was it yes, thanks and sorry for wasting your time one something like this. Just a little bit of brain fog on my part.
